### ISSUE TITLE
Add "mariadbent" as an additional auto-connection method (similar to "cleardb")

### ISSUE THREAD

**Issue by b-io** [pivotal-cf/PivotalMySQLWeb#10]
Hello gentlemen,

I have slightly modified the code to handle the default Swsisscom "VCAP_SERVICES" (it is the main Swiss telecom company). They use "mariadbent" instead of "cleardb" as follows:
{
  "VCAP_SERVICES": {
    "mariadbent": [
      {
        "label": "mariadbent",
        ... and then it is the same as cleardb
}
Could you be kind to add "mariadbent" in the LoginController as an additional auto-connection method? That would be fantastic! I really like your web GUI :) Thanks!

Florian
barras.io

**Comment by papicella** [comment]
Hi,

Happy to do that. I don't have the mariadbent service to test this though so if you just provide the code snippet you have (Utils.parseLoginCredentials) I will feel confident I have added it correctly. I understand it's like clearDB so in theory should be straight forward but I always like to test code once before I commit it.

Thanks.

**Comment by b-io** [comment]
Hi,
Thanks for the quick reply!
Yes, with pleasure:
`
	public static Login parseLoginCredentials(String jsonString) {
		log.info("Obtaining VCAP_SERVICES credentials - mariadbent");

		Login login = new Login();
		JsonParser parser = JsonParserFactory.getJsonParser();
		log.info(parser.toString());
		Map<String, Object> jsonMap = parser.parseMap(jsonString);

		List mysqlService = (List) jsonMap.get("mariadbent");
		Map cfMySQLMap = null;
		Map credentailsMap = null;

		cfMySQLMap = (Map) mysqlService.get(0);
		credentailsMap = (Map) cfMySQLMap.get("credentials");
		login.setUrl((String) credentailsMap.get("jdbcUrl") + "&connectTimeout=1800000&socketTimeout=1800000&autoReconnect=true&reconnect=true");

		login.setUsername((String) credentailsMap.get("username"));
		login.setPassword((String) credentailsMap.get("password"));
		login.setSchema((String) credentailsMap.get("name"));

		return login;
	}
`
I have just replaced cleardb by mariadbent :)
Thank you!

Florian

**Comment by papicella** [comment]
Ok all done, can you test and confirm this new code works for you? If it does I will mark issue as resolved.

Thanks.

**Comment by b-io** [comment]
This works perfectly! Thank you 👍

**Comment by papicella** [comment]
Awesome thanks..
