### ISSUE TITLE
user/db switcher for handling multiple database instances

### ISSUE THREAD

**Issue by t-kasi** [pivotal-cf/PivotalMySQLWeb#11]
With PivotalMySQL*Web you currently can connect to one(!) MySQL service instance only.
If you are using multiple db instances, as we do with our microservice architecture, this leads to the multiple PivotalMySQL*Web apps running on a PCF (which is ugly and ressource costly).
It would be great to have a user/db switcher (e.g. top right corner, where you see the logged in user already) in the PivotalMySQL*Web so that you could handle multiple mySQL instances with only one PivotalMySQL*Web app being installed on a PCF.

Thanks a lot in advance!

**Comment by papicella** [comment]
Done
