### ISSUE TITLE
The file ./target/PivotalMySQLWeb-1.0.0-SNAPSHOT.jar doesn't exist

### ISSUE THREAD

**Issue by alsarah** [pivotal-cf/PivotalMySQLWeb#14]
Hello, 

I am trying to deploy this app to PCF but I can't find the relevant .jar file ./target/PivotalMySQLWeb-1.0.0-SNAPSHOT.jar in this repo. Please advise.

Thank you

**Comment by papicella** [comment]
You can download the JAR from here:

https://drive.google.com/a/pivotal.io/file/d/1aiMe_K70c_hScxJPdWJPy3nEg1tnoYGV/view?usp=sharing

BUT what you need to do is build it yourself using the steps in he README.md

git clone https://github.com/pivotal-cf/PivotalMySQLWeb.git
cd PivotalMySQLWeb
./mvnw -DskipTests=true package
