### ISSUE TITLE
SSO as alternative to basic auth

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/PivotalMySQLWeb#15]
In order to prevent unauthorized access to pivotal-mysql-web and/or stale & recycled passwords, it would be beneficial to be able to secure this with an [SSO plan](https://github.com/pivotal-cf/docs-identity) (e.g., a whitelisted user group, whitelisted user group with read-only privileges, whitelisted user group with admin privileges, etc.) as an alternative to basic auth.

Thoughts?

Thanks for your time! 👍

**Comment by papicella** [comment]
Yeah makes sense BUT can this be done without breaking the app which can run stand-alone outside of PCF and won't break if no SSO service bound etc? This is a separate repo which was created that added support for pivotal SSO marketplace service outside of this repo. That repo is this one which I did not create

https://github.com/pivotalservices/mysql-web-sso
