### ISSUE TITLE
Global Instrumentation

### ISSUE THREAD

**Issue by nickypike** [pivotal-cf/PivotalMySQLWeb#16]
From what I'm seeing, this must be deployed in the Org/Space to connect to instances.  Is it possible to allow configuration so that the app can be deployed as global app (i.e., system/system) and allow every tenant the ability to use it from a single instance?  Doesn't seem efficient to require the app to be deployed multiple times.

**Comment by papicella** [comment]
Hi,

You can select not to bind to a service and it will prompt you for login details where you provide the login details to any MySQL instance in any org/space as long as it can reach the endpoint which inside PCF Diego cells should work BUT that means yu need the connection details to do that. Binding will take care of that for you BUT not when you decide not to bind to a MySQL instance

I also add the ability within an ORG/SPACE to bind to multiple MySQL service instance and switch between them in the navigation bar as required

**Comment by papicella** [comment]
Closed as you can deploy in an org/space and bind to multiple instances so users can switch to the MySQL they want to use or just deploy in a system org/space and use the connect details to connect to a MySQL outside of that ORG/SPACE

**Comment by ichandan16** [comment]
Hi I tried to push the application not binding to any mysql-service. Once I put default user name and password, it shows me the dialog box to input username, password and JDBC string. Providing the details, throws bad credential and display me the intital login page where we are providing the default credentials.
