### ISSUE TITLE
Suggestion: Configurable Table Viewer Configurable Max Records

### ISSUE THREAD

**Issue by yuya-iwabuchi** [pivotal-cf/PivotalMySQLWeb#17]
Hello,

I have noticed there's a hardcoded limit of 30 rows to be pulled for when viewing a table from the table's Sample Data page. Here's where I see the limit in the code:
https://github.com/pivotal-cf/PivotalMySQLWeb/blob/a207a32483c2d97bc62a8128c4c45339b1d65d52/src/main/java/com/pivotal/pcf/mysqlweb/controller/TableViewerController.java#L40
I'd like to suggest this to become a configurable parameter, perhaps next to the "Show ** Entities" on the page.

Thanks,
Yuya

**Comment by papicella** [comment]
yeah, this is an easy fix so will do this shortly. The support for this already exists just not wired in to use it. Keep this open and will let you know when added

**Comment by yuya-iwabuchi** [comment]
Thanks! Much appreciated.

**Comment by papicella** [comment]
Hi,

This is now complete. Just go to preferences and set the number of rows you wish to see on the table viewer sample data size and it will now use that. You will need to package and rebuild and re-deploy. You can also set the desired preferences inside src/main/resources/preferences.properties if you like

Closing but if it doesn't work let me know it should I tested it
