### ISSUE TITLE
Are there custom formatting rules for this repository?

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/PivotalMySQLWeb#8]
In order for contributors to format their code to spec, it would be helpful for some sort of `formatting_rules.xml` to be committed to this repository.

Extended rationale: my colleagues and I would be interested in contributing code here and there to this project, but would find it helpful if the formatting rules were included. I use the standard formatting provided by Springtoolsuite, so if I were to make local changes and apply my formatter it would change eevvvverrythiinngg.

Thanks for your time

**Comment by papicella** [comment]
No there is not on this repo. I appreciate you looking at this project
