### ISSUE TITLE
Consider leveraging lombok

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/PivotalMySQLWeb#9]
In order to reduce overall lines of code, a maintainer should evaluate whether [`lombok` annotations would be appropriate for this project](https://projectlombok.org/features/Data).

Quick wins introducing minimal cognitive overhead:

- `@data` to generate getters/setters/hashcode/toString for POJOs
- `@slf4` to auto-generate a `logger`

**Comment by papicella** [comment]
Agree and I will do that early next week and commit my changes. I have not updated this for a while so their are many things that could be fixed here

**Comment by aegershman** [comment]
Cool beans. I didn't mean to sound presumptive with opening some of these minor issues/PRs against this, zero urgency or anything, I just figured I'd log them as suggestions/ideas; it's an awesome project, thank you for making it OSS + maintaining it 👍

**Comment by papicella** [comment]
No problem at all I appreciate your looking and wanting to get involved

**Comment by papicella** [comment]
I have now added lombok annotations to this project. Both @data and @slf4j have been used and this has simplified the code a little as a result.

Thanks for the suggestions
